### ISSUE TITLE
missing docker-compose.yml for example 06

### ISSUE THREAD

**Issue by dirksiemers** [dnhsoft/sw-docker-demo#1]
Hi, I saw your presentation on the SCD16 and I´m interested the 6th example, but I think you forgot to commit the docker-compose.yml

Would you like to add the file?

**Comment by chudomir-delchev-dnh** [comment]
Hi, that example was mounted in Example 04.

However, I have modified it and it has it's own directory now - https://github.com/dnhsoft/sw-docker-demo/tree/master/06-develop-a-plugin/.docker

See also the helper scripts:

You can call ./restart-containers.sh and then some of the 2 init scripts to setup the shop.

Let me know if there are any other troubles.

I'll add soon such helper scripts for most of the examples.

**Comment by dirksiemers** [comment]
thx
